export const ADD_sport = 'ADD_sport';
export const REMOVE_sport = 'REMOVE_sport';
export const UPDATE_PRICE = 'UPDATE_PRICE';

export const SUBMIT_WORKOUT_SUCCESS = 'SUBMIT_WORKOUT_SUCCESS';
export const SUBMIT_WORKOUT_FAILED = 'SUBMIT_WORKOUT_FAILED';
export const SUBMIT_WORKOUT_START = 'SUBMIT_WORKOUT_START';
export const SUBMIT_WORKOUT_INIT = 'SUBMIT_WORKOUT_INIT';

export const VIEW_HISTORY_START = 'VIEW_HISTORY_START';
export const VIEW_HISTORY_SUCCESS = 'VIEW_HISTORY_SUCCESS';
export const VIEW_HISTORY_FAILED = 'VIEW_HISTORY_FAILED';
